name = "winter-bar-aae0"
workers_dev = true
compatibility_date = "2023-03-06"
account_id="4bf90431d5a161c80b07ac520cd4337b"
main = "src/worker.mjs"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "Room" },
]

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

# Indicate that you want the Room classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Room"]
